blank_issues_enabled: false
contact_links:
  - name: Roadmap
    url: https://github.com/widgemo/igloo-feedback/issues?q=label%3Aroadmap
    about: See what is planned for the free version and for Igloo Pro.
